# -*- coding: utf-8 -*-
"""MySubscriptions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1FL8CsHHvtfXLUq4ogi7NueEz4xeZBp
"""

from typing import List

class Subscription:
  def __init__(self, name, mo, tu, we, th, fr, sa, su):
    self.name = name
    self.monday = mo
    self.tuesday = tu
    self.wednesday = we
    self.thursday = th
    self.friday = fr
    self.saturday = sa
    self.sunday = su

  def get_cost(self) -> float:
    return self.monday + self.tuesday + self.wednesday + self.thursday + self.friday + self.saturday + self.sunday



def get_pairs(arr: List[Subscription], budget: int):
  ans = []
  n = len(arr)
  for i in range(n):
    for j in range(i+1, n):
      summation = arr[i].get_cost() + arr[j].get_cost()
      if summation <= budget:
        ans.append({arr[i].name, arr[j].name})
  return ans

if __name__ == '__main__':
  TOI = Subscription(name="TOI", mo=3, tu=3, we=3, th=3, fr=3, sa=5, su=6)
  Hindu = Subscription(name="Hindu", mo=2.5, tu=2.5, we=2.5, th=2.5, fr=2.5, sa=4, su=4)
  ET = Subscription(name="ET", mo=4, tu=4, we=4, th=4, fr=4, sa=4, su=10)
  BM = Subscription(name="BM", mo=1.5, tu=1.5, we=1.5, th=1.5, fr=1.5, sa=1.5, su=1.5)
  HT = Subscription(name="HT", mo=2, tu=2, we=2, th=2, fr=2, sa=4, su=4)

  inputs = [TOI, Hindu, ET, BM, HT]
  budget = 40
  get_pairs(inputs, budget)

